"""Generate a private standalone review page with stable resource/metadata IDs."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
rows=[]
for p in sorted((ROOT/'localization/en-US').glob('korean-batch-*.jsonl'))+[ROOT/'localization/en-US/supplemental-display.jsonl']:
    for line in p.read_text().splitlines():
        r=json.loads(line);rows.append(dict(id=f'R{len(rows)+1:03d}',batch=p.stem,ko=r['original'],en=r['target'],zh=r.get('chinese_reference') or '',notes='\n'.join(r.get('notes',[])),location=r.get('object_name','')+' / '+json.dumps(r['reference'],ensure_ascii=False)))
for i,r in enumerate(json.loads((ROOT/'localization/en-US/metadata-drafts.json').read_text()),1):
    rows.append(dict(id=f'M{i:03d}',batch='metadata',ko=r['original'],en=r['target'],zh=r.get('chinese_reference') or '',notes='\n'.join(r.get('notes',[])),location=json.dumps(r['reference'],ensure_ascii=False)))
profile=json.loads((ROOT/'localization/mods/zephyr-passives-2.4.3.json').read_text())
for i,r in enumerate(profile['overrides'],1):
    rows.append(dict(id=f'P{i:03d}',batch='ZephyrPassives 2.4.3 (default settings)',ko=r['original'],en=r['target'],zh='',notes='Optional mod profile. Assumes ZephyrPassives 2.4.3 with default settings. Base English: '+r['base_target']+'\nMod behavior source: '+profile['source'],location=json.dumps(r['reference'],ensure_ascii=False)))
fullmap=json.loads((ROOT/'localization/mods/zephyr-fullmap-1.8.0.json').read_text())
for i,r in enumerate(fullmap['rows'],1):
    rows.append(dict(id=f'F{i:03d}',batch='ZephyrFullmap 1.8.0 English',ko=r['original'],en=r['target'] or '(Destination suffix omitted)',zh='',notes=r['notes'],location='Fullmap plugin display text'))
page=r'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Zephyr translation review</title>
<style>body{font:16px/1.6 system-ui,sans-serif;margin:0;background:#f4f3ef;color:#20262b}header{position:sticky;top:0;background:#fff;padding:18px 4%;border-bottom:1px solid #bbb}h1{font-size:24px;margin:0}input,select,button{font:inherit;padding:6px;margin:4px}input{width:36%}main{max-width:1250px;margin:20px auto;padding:0 20px}article{background:white;border:1px solid #ccc;border-radius:8px;padding:18px;margin-bottom:18px}.texts{display:grid;grid-template-columns:1fr 1fr;gap:24px}.text{white-space:pre-wrap;overflow-wrap:anywhere}h2{font-size:16px;color:#365c69}summary{cursor:pointer}small{color:#556}pre{white-space:pre-wrap;overflow-wrap:anywhere}#count{margin:4px}@media(max-width:650px){.texts{grid-template-columns:1fr}input{width:90%}header{position:static}}</style>
<header><h1>Zephyr · Korean–English review / 번역 검토</h1><small>Includes optional ZephyrPassives review (P IDs). Korean is authoritative. Chinese is supporting context. Names without approval remain provisional.</small><br>
<input id="query" placeholder="Search ID, Korean, English, notes…"><select id="batch"><option value="">All batches</option></select><button id="prevSection">Previous section</button><button id="nextSection">Next section</button><br><button id="prev">Previous page</button><button id="next">Next page</button><div id="count"></div></header>
<main><p>Review at your own pace. Send corrections as <b>R123 — suggested English / reason</b>. M001–M030 refer to hard-coded text. Control codes are shown literally; this page is read-only and works offline. / 검토 번호와 수정안을 보내 주세요.</p><noscript>This viewer does not run JavaScript. Open the private review address in Safari, or use the static Sections/TXT review.</noscript><div id="items"></div></main>
<script id="data" type="application/json">DATA</script><script>
const rows=JSON.parse(document.getElementById('data').textContent), q=document.getElementById('query'), batch=document.getElementById('batch'), items=document.getElementById('items');let page=0;const size=50;
const sections=[...new Set(rows.map(r=>r.batch))];for(const b of sections){const o=document.createElement('option');o.value=b;o.textContent=b;batch.append(o)}
function node(tag,text,parent){const n=document.createElement(tag);n.textContent=text;parent.append(n);return n}
function render(){const term=q.value.toLocaleLowerCase();const found=rows.filter(r=>(!batch.value||r.batch===batch.value)&&(!term||[r.id,r.ko,r.en,r.zh,r.notes,r.location].join(' ').toLocaleLowerCase().includes(term)));page=Math.max(0,Math.min(page,Math.ceil(found.length/size)-1));items.replaceChildren();for(const r of found.slice(page*size,(page+1)*size)){const a=node('article','',items);a.id=r.id;node('h2',r.id+' · '+r.batch,a);const grid=node('div','',a);grid.className='texts';for(const [label,text] of [['한국어 원문',r.ko],['English',r.en]]){const col=node('section','',grid);node('small',label,col);node('div',text,col).className='text'}const d=node('details','',a);node('summary','Chinese reference · Notes · Resource',d);node('pre',(r.zh||'(No Chinese reference)')+'\n\n'+r.notes+'\n\n'+r.location,d)}document.getElementById('count').textContent=found.length+' matches · page '+(page+1)+' / '+Math.max(1,Math.ceil(found.length/size))+' · '+rows.length+' total entries';document.getElementById('prev').disabled=page===0;document.getElementById('next').disabled=(page+1)*size>=found.length}
function changeSection(step){const current=sections.indexOf(batch.value);const next=current<0?0:Math.max(0,Math.min(sections.length-1,current+step));batch.value=sections[next];q.value='';page=0;render();window.scrollTo(0,0)}document.getElementById('prevSection').onclick=()=>changeSection(-1);document.getElementById('nextSection').onclick=()=>changeSection(1);const params=new URLSearchParams(location.search);q.value=params.get('q')||'';batch.value=q.value?'':sections[0];q.oninput=()=>{batch.value='';page=0;render()};batch.onchange=()=>{page=0;render()};document.getElementById('prev').onclick=()=>{page--;render()};document.getElementById('next').onclick=()=>{page++;render()};render();</script></html>'''
page=page.replace('DATA</script>',json.dumps(rows,ensure_ascii=False).replace('<','\\u003c')+'</script>')
out=ROOT/'private/Zephyr-Translation-Review.html';out.write_text(page);print(f'{out}: {len(rows)} entries')
